((emoji--command-Emoji nil)
 (emoji--command-Emoji\ >\ Body nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand\ >\ fingers-open nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand\ >\ fingers-open\ 🖖 nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink\ >\ food nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink\ >\ food\ >\ fruit nil)
 (emoji--command-Emoji\ >\ Smileys nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ neutral-skeptical nil)
 (emoji--command-Recent nil))
